version: '3.1'

services:

  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 5433:8080

